newsite/newsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

newsite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('information/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

newsite/polls/models.py
import datetime

from django.db import models
from django.db.models import CharField
from django.utils import timezone, dateparse


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self) -> CharField:
        return self.question_text

    def was_published_recently(self) -> bool:
        now = timezone.now()
        pub_date = dateparse.parse_datetime(self.pub_date.__str__())
        return now - datetime.timedelta(days=1) <= pub_date <= now
        # return 'yes' if (now - datetime.timedelta(days=1) <= pub_date <= now) else 'no'

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> CharField:
        return self.choice_text

newsite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    # model = Question
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions (not including those set to be published in the future)."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    # model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """Excludes any questions that aren't published yet."""

        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request: HttpRequest, question_id: int):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question, 'error_mes': "You didn't select a choice"})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

newsite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>

<div>
    <h1>{{ question.question_text }}</h1>
</div>

{% if error_mes %}
<div>
    <p><strong>{{ error_mes }}</strong></p>
</div>
{% endif %}

<div>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        <div>{% csrf_token %}</div>

        <div>
            {% for choice in question.choice_set.all %}

            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>

            {% endfor %}
        </div>

        <div>
            <input type="submit" value="Vote">
        </div>
    </form>
</div>

<div>
    <a href="{% url 'polls:index' %}">all questions</a>
</div>

</body>
</html>

newsite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>

<div>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">
                {{ question.question_text }}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>

</body>
</html>

newsite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>

<div>
    <h1>{{ question.question_text }}</h1>
</div>

<div>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
</div>

<div>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>

</body>
</html>

newsite/polls/templates/polls/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>

<div>
    {{ resp_str }}

    <hr/>
    <a href="/polls">back</a>
</div>

</body>
</html>